version: "3.9"
services:
  app:
    build: .
    ports:
      - 8080
    networks:
      - app
  nginx:
    image: "nginx:1.18-alpine"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ops/tls:/etc/nginx/certs
    networks:
      - app
    ports:
      - 80:80
      - 443:443

networks:
  app:
